name: ssnp
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: apt update && apt-get install g++ cmake -y
      - run: |
          cmake -B build -S .
          cmake --build build
          ./build/ssnp_cpp
